### ISSUE TITLE
rake swaggerize doesn't create directories

### ISSUE THREAD

**Issue by drewish** [rswag/rswag#15]
I edited `spec/swagger_helper.rb` to change the directory name to reflect a date based versioning scheme:

```
  config.swagger_docs = {
    'v2016-09-01/swagger.json' => {
      swagger: '2.0',
      info: {
        title: 'Blah API',
        version: 'v2016-09-01'
      }
    }
  }
```

And when I ran the rake task it died because the directory didn't exist:

```
% bundle exec rake swaggerize
/Users/andrew/.rbenv/versions/2.3.1/bin/ruby -I/Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib:/Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format SwaggerRails::RSpec::Formatter --dry-run --order defined
Generating Swagger Docs ...
/Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/swagger_rails-5003b7ccd9ff/lib/swagger_rails/rspec/formatter.rb:32:in `initialize': No such file or directory @ rb_sysopen - /Users/andrew/projects/accounting_integration/swagger/v2016-09-01/swagger.json (Errno::ENOENT)
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/swagger_rails-5003b7ccd9ff/lib/swagger_rails/rspec/formatter.rb:32:in `open'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/swagger_rails-5003b7ccd9ff/lib/swagger_rails/rspec/formatter.rb:32:in `block in stop'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/swagger_rails-5003b7ccd9ff/lib/swagger_rails/rspec/formatter.rb:29:in `each'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/swagger_rails-5003b7ccd9ff/lib/swagger_rails/rspec/formatter.rb:29:in `stop'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:189:in `block in notify'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:188:in `each'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:188:in `notify'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:183:in `stop'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:157:in `block in finish'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:175:in `close_after'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:156:in `finish'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:79:in `report'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:111:in `run_specs'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:87:in `run'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:71:in `run'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:45:in `invoke'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/exe/rspec:4:in `<main>'
```

Running `mkdir swagger/v2016-09-01` and then `rake swaggerize` again fixed it.

It seems like it should just create any directories it needs or at least handle it a bit more gracefully.

**Comment by drewish** [comment]
I'm going to close this. Here's how I handled it in my gem if you're interested: https://github.com/drewish/rspec-rails-swagger/blob/master/lib/rspec/rails/swagger/formatter.rb#L73-L80
