### ISSUE TITLE
Raised UnexpectedResponse when using active_model_serializer

### ISSUE THREAD

**Issue by belgoros** [rswag/rswag#170]
I'm using [active_model_serializer](https://github.com/rails-api/active_model_serializers) with a Rails API to render JSON and can't figure out why the below test raises `UnexpectedResponse` exception:
```
path '/languages/{id}' do
    get 'Retrieves a language by ID' do
      tags 'Languages'
      security [ oauth2: [] ]
      parameter name: :id, in: :path, type: :string
      parameter name: :Authorization, in: :header, type: :string

      response '200', 'Language found' do
        schema type: :object,
          properties: {
            id:  { type: :integer },
            tag: { type: :string }
          },
          required: [:id]

        let(:user) { create(:user) }
        let(:headers) { valid_headers(user.username) }
        let(:Authorization) { headers['Authorization'] }
        let(:id) { Language.create(tag: 'tt-TT').id }

        run_test!
      end
    end
  end
```
Here is the error:
```
1) Languages API /languages/{id} get Language found returns a 200 response
     Failure/Error: raise UnexpectedResponse, "Expected response body to match schema: #{errors[0]}" if errors.any?
     
     Rswag::Specs::UnexpectedResponse:
       Expected response body to match schema: The property '#/' did not contain a required property of 'id' in schema 980d621b-6289-58db-9a7f-69b705750e27
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:48:in `validate_body!'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:19:in `validate!'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:31:in `assert_response_matches_metadata'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:91:in `block in run_test!'
```
I put some `puts` statements into `response_validator.rb`:
```
module Rswag
  module Specs
    class ResponseValidator
...
def validate_body!(metadata, swagger_doc, body)
        response_schema = metadata[:response][:schema]
        return if response_schema.nil?

        validation_schema = response_schema
          .merge('$schema' => 'http://tempuri.org/rswag/specs/extended_schema')
          .merge(swagger_doc.slice(:definitions))
          puts "+++++ validation_schema: #{validation_schema}"
          puts "++++++ body: #{body}"
        errors = JSON::Validator.fully_validate(validation_schema, body)
        raise UnexpectedResponse, "Expected response body to match schema: #{errors[0]}" if errors.any?
      end
```
and it seems like there are no errors in `validation_schema` and `body` hashes that look like that:
```
+++++ validation_schema: {:type=>:object, :properties=>{:id=>{:type=>:integer}, :tag=>{:type=>:string}}, :required=>[:id], "$schema"=>"http://tempuri.org/rswag/specs/extended_schema"}
++++++ body: {"data":{"id":"1","type":"languages","attributes":{"tag":"tt-TT"}}}
```
What's wrong with that, please ?

**Comment by belgoros** [comment]
Here is how `show`action looks like in `LanguagesController`:
```
module V1
  class LanguagesController < ApplicationController
    before_action :find_language, only: :show

def show
  json_response @language
end

private

    def find_language
      @language = Language.find(params[:id])
    end
```
Method `json_response` is defined in `controllers/concerns/response.rb` as follows:
```
module Response
  extend ActiveSupport::Concern

  def json_response(object, status = :ok, opts = {})
    response = {json: object, status: status}.merge(opts)
    render response
  end

  def respond_with_errors(object)
    render json: { errors: ErrorSerializer.serialize(object) }, status: :unprocessable_entity
  end
end
```
If I change the `show` action return value to a standard json:
```
   def show
      render json: @language.to_json
    end
```
then `validation_schema` and `body` values have no `data` not `attributes` keys:
```
+++++ validation_schema: {:type=>:object, :properties=>{:id=>{:type=>:integer}, :tag=>{:type=>:string}}, :required=>[:id], "$schema"=>"http://tempuri.org/rswag/specs/extended_schema"}
++++++ body: {"data":{"id":"1","type":"languages","attributes":{"tag":"fr-GS"}}}
````
and the test passes.

**Comment by jtannas** [comment]
heyo - sorry it took >3 years to get a reply. I'm a new volunteer clearing out the backlog of issues and came across this.

From the look of it your expected response schema looks like:
```
{
	id:  { type: :integer },
	tag: { type: :string }
}
```
And you actual response schema looks like:
```ruby
{
	"data": {
		"id":"1", # string instead of integer
		"type":"languages",
		"attributes": {
			"tag": "tt-TT"
		}
	}
	# no id property in base level properties
	# no tag property in base level properties
}
```

Seems like a pretty significant mismatch :sweat_smile: 

---

Anyhoooo... since it's been so long since this was opened I'm going to close it under the assumption that it's no longer relevant to you.
If I'm mistaken and you're still running into problems just make another issue and I'll be happy to help :)
Cheers!
