### ISSUE TITLE
RSpec 'pending' method is ignored when used in an example

### ISSUE THREAD

**Issue by belgoros** [rswag/rswag#171]
It seems like RSpec `pending` method has no effects when used in a rswag example:
```
path '/languages/{id}' do    
    get 'Retrieves a language by ID' do
      tags 'Languages'
      security [ oauth2: [] ]
      parameter name: :id, in: :path, :type => :string
      parameter name: :Authorization, in: :header, type: :string

      response '200', 'Language found' do
        pending "Should work with JSON API structure used by AMS"
        
        let(:user)    { create(:user) }
        let(:headers) { valid_headers(user.username) }
        let(:Authorization) { headers['Authorization'] }
        let(:id) { create(:language).id }

        schema type: :object,
          properties: {
            data: {
              type: :object,
              properties: {
                id:  { type: :integer },
                type: { type: :string },
                attributes: {
                  type: :object,
                  properties: {
                    tag: { type: :string }                    
                  }
                }                
              }
            }
          },

        required: ['id']
        run_test!
      end
```
After running it, it prints the pending feature but marks it as `failing`:
```
Run options: include {:locations=>{"./spec/integration/languages_spec.rb"=>[34]}}
*F

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Languages API /languages/{id} get Language found Should work with JSON API structure used by AMS
     # Not yet implemented
     # ./spec/integration/languages_spec.rb:35


Failures:

  1) Languages API /languages/{id} get Language found returns a 200 response
     Failure/Error: raise UnexpectedResponse, "Expected response body to match schema: #{errors[0]}" if errors.any?
     
     Rswag::Specs::UnexpectedResponse:
       Expected response body to match schema: The property '#/data/id' of type string did not match the following type: integer in schema 250374af-70ce-591d-ab32-3645880fff40
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:46:in `validate_body!'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:19:in `validate!'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:31:in `assert_response_matches_metadata'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:91:in `block in run_test!'

Finished in 0.50693 seconds (files took 1.08 seconds to load)
2 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/integration/languages_spec.rb:34 # Languages API /languages/{id} get Language found returns a 200 response
```

**Comment by jtannas** [comment]
Heyo - I just joined in on the project and am helping sort through our issue backlog.
It looks like the issue here is that the `pending` is actually a different spec than the one that's failing.

You can see in the output that there were two test results
> `2 examples, 1 failure, 1 pending`

The one that's failing is the `run_test!` that's further down in your code.

**Comment by belgoros** [comment]
@jtannas Hey, unfortunately, I have no more access to the project code source (4 years ago), so it's impossible to reproduce the issue.
