### ISSUE TITLE
how to generate /api-docs/v1/swagger.json for my rails api?

### ISSUE THREAD

**Issue by seyhaheng2** [rswag/rswag#192]
when i go to this url http://localhost:3000/api-docs/index.html it's show me like this 
Not Found /api-docs/v1/swagger.json

so how can i generate swagger.json file?

**Comment by jaydorsey** [comment]
You need to run `rake rswag:specs:swaggerize` to generate the json file

**Comment by nidhi-canopas** [comment]
Getting following error when running `rake rswag:specs:swaggerize` : 
Ruby version : 3.0.1
Rails : 6.1.3

````rake rswag:specs:swaggerize
/home/nidhi/.rbenv/versions/3.0.1/bin/ruby -I/home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib:/home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-support-3.10.2/lib /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
No examples found.
/home/nidhi/togness-api-web/spec/swagger_helper.rb:3:in `require': cannot load such file -- rails_helper (LoadError)
        from /home/nidhi/togness-api-web/spec/swagger_helper.rb:3:in `<top (required)>'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:5:in `require'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:5:in `<top (required)>'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:235:in `require'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:235:in `rescue in custom_formatter'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:232:in `custom_formatter'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:183:in `find_formatter'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:152:in `add'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:974:in `add_formatter'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `block in load_formatters_into'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `each'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `load_formatters_into'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:24:in `configure'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:132:in `configure'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:99:in `setup'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
/home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `block in custom_formatter': uninitialized constant Rswag (NameError)
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `each'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `inject'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `custom_formatter'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:183:in `find_formatter'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:152:in `add'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:974:in `add_formatter'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `block in load_formatters_into'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `each'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `load_formatters_into'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:24:in `configure'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:132:in `configure'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:99:in `setup'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
        from /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
/home/nidhi/.rbenv/versions/3.0.1/bin/ruby -I/home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib:/home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-support-3.10.2/lib /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined failed
````

**Comment by alexohneander** [comment]
I have exactly the same error:
Rails: 6.1.4.1
Ruby: ruby 3.0.0p0
```bash
rake rswag:specs:swaggerize
/Users/alex/.rvm/rubies/ruby-3.0.0/bin/ruby -I/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib:/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-support-3.10.2/lib /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
No examples found.
/Users/alex/Projects/Ruby/lan_house/ms_house_api/spec/swagger_helper.rb:3:in `require': cannot load such file -- rails_helper (LoadError)
	from /Users/alex/Projects/Ruby/lan_house/ms_house_api/spec/swagger_helper.rb:3:in `<top (required)>'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:5:in `require'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:5:in `<top (required)>'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:235:in `require'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:235:in `rescue in custom_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:232:in `custom_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:183:in `find_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:152:in `add'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:974:in `add_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `block in load_formatters_into'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `each'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `load_formatters_into'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:24:in `configure'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:132:in `configure'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `block in custom_formatter': uninitialized constant Rswag (NameError)
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `each'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `inject'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `custom_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:183:in `find_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:152:in `add'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:974:in `add_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `block in load_formatters_into'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `each'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `load_formatters_into'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:24:in `configure'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:132:in `configure'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
/Users/alex/.rvm/rubies/ruby-3.0.0/bin/ruby -I/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib:/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-support-3.10.2/lib /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined failed
```

**Comment by sg552** [comment]
the error message is saying it doesn't have any test example. and it can not load `rails_helper`

so first of all, you have to add spec to rails ( see rspec-rails and rspec gem for details )
then, you have to write integeration spec test cases to rails, 
then, you can run 'rswag:specs:swaggerize' command to generate swagger (yml or json) files
then, you can visit '/api/docs' , to see a UI page like postman , and test your API methods.

the official document needs to be updated.

> Getting following error when running `rake rswag:specs:swaggerize` : Ruby version : 3.0.1 Rails : 6.1.3
> 
> ```ruby
> /home/nidhi/.rbenv/versions/3.0.1/bin/ruby -I/home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib:/home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-support-3.10.2/lib /home/nidhi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
> No examples found.
> /home/nidhi/togness-api-web/spec/swagger_helper.rb:3:in `require': cannot load such file -- rails_helper (LoadError)
>         from /home/nidhi/togness-api-web/spec/swagger_helper.rb:3:in `<top (required)>'

**Comment by harisishfaq07** [comment]
> when i go to this url http://localhost:3000/api-docs/index.html it's show me like this Not Found /api-docs/v1/swagger.json
> 
> so how can i generate swagger.json file?

hi @seyhaheng2 I think you upgrade your rails from older to 5+ or might be missed some files.
please add these files to your directories.

**/spec/rails_helper.rb**
```
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'
abort('The Rails environment is running in production mode!') if Rails.env.production?
require 'rspec/rails'
begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end
RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true
  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!
end
```

next 
**/spec/spec_helper.rb**
```

# frozen_string_literal: true

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
    # rspec-expectations config goes here. You can use an alternate
    # assertion/expectation library such as wrong or the stdlib/minitest
    # assertions if you prefer.
    config.expect_with :rspec do |expectations|
      # This option will default to `true` in RSpec 4. It makes the `description`
      # and `failure_message` of custom matchers include text for helper methods
      # defined using `chain`, e.g.:
      #     be_bigger_than(2).and_smaller_than(4).description
      #     # => "be bigger than 2 and smaller than 4"
      # ...rather than:
      #     # => "be bigger than 2"
      expectations.include_chain_clauses_in_custom_matcher_descriptions = true
    end
  
    # rspec-mocks config goes here. You can use an alternate test double
    # library (such as bogus or mocha) by changing the `mock_with` option here.
    config.mock_with :rspec do |mocks|
      # Prevents you from mocking or stubbing a method that does not exist on
      # a real object. This is generally recommended, and will default to
      # `true` in RSpec 4.
      mocks.verify_partial_doubles = true
    end
  
    # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
    # have no way to turn it off -- the option exists only for backwards
    # compatibility in RSpec 3). It causes shared context metadata to be
    # inherited by the metadata hash of host groups and examples, rather than
    # triggering implicit auto-inclusion in groups with matching metadata.
    config.shared_context_metadata_behavior = :apply_to_host_groups
  
    # The settings below are suggested to provide a good initial experience
    # with RSpec, but feel free to customize to your heart's content.
    #   # This allows you to limit a spec run to individual examples or groups
    #   # you care about by tagging them with `:focus` metadata. When nothing
    #   # is tagged with `:focus`, all examples get run. RSpec also provides
    #   # aliases for `it`, `describe`, and `context` that include `:focus`
    #   # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
    #   config.filter_run_when_matching :focus
    #
    #   # Allows RSpec to persist some state between runs in order to support
    #   # the `--only-failures` and `--next-failure` CLI options. We recommend
    #   # you configure your source control system to ignore this file.
    #   config.example_status_persistence_file_path = "spec/examples.txt"
    #
    #   # Limits the available syntax to the non-monkey patched syntax that is
    #   # recommended. For more details, see:
    #   # https://relishapp.com/rspec/rspec-core/docs/configuration/zero-monkey-patching-mode
    #   config.disable_monkey_patching!
    #
    #   # Many RSpec users commonly either run the entire suite or an individual
    #   # file, and it's useful to allow more verbose output when running an
    #   # individual spec file.
    #   if config.files_to_run.one?
    #     # Use the documentation formatter for detailed output,
    #     # unless a formatter has already been configured
    #     # (e.g. via a command-line flag).
    #     config.default_formatter = "doc"
    #   end
    #
    #   # Print the 10 slowest examples and example groups at the
    #   # end of the spec run, to help surface which specs are running
    #   # particularly slow.
    #   config.profile_examples = 10
    #
    #   # Run specs in random order to surface order dependencies. If you find an
    #   # order dependency and want to debug it, you can fix the order by providing
    #   # the seed, which is printed after each run.
    #   #     --seed 1234
    #   config.order = :random
    #
    #   # Seed global randomization in this process using the `--seed` CLI option.
    #   # Setting this allows you to use `--seed` to deterministically reproduce
    #   # test failures related to randomization by passing the same `--seed` value
    #   # as the one that triggered the failure.
    #   Kernel.srand config.seed
  end
```
Next stop your server and rerun
on browser run: localhost:3000/api-docs

Hope this will work for you.

**Comment by harisishfaq07** [comment]
> 

hi @nidhi-canopas , hope this will work for you 
https://github.com/rswag/rswag/issues/192#issuecomment-1425626298

**Comment by harisishfaq07** [comment]
> will work for you

hi @alexohneander , hope this will work for you.

https://github.com/rswag/rswag/issues/192#issuecomment-1425626298
