### ISSUE TITLE
unable to use a params `type: :file, in: :body`

### ISSUE THREAD

**Issue by ngouy** [rswag/rswag#216]
working code : 

```rb
my_file = File.open('spec/data/test-image.png')

my_request = HTTParty.post(
    '<approot>/api/file_upload',
    body: { file: my_file },
)
```

but when using

```rb
path '/api/file_upload' do
    post 'Update a file' do
        tags TAGS_API_FILE_UPLOAD
        produces 'application/json'
        consumes 'application/json'

        parameter name: :file, in: :body, type: :file

       response '200', 'file uploaded' do
          let(:file) { File.open('spec/data/test-image.png') }

          run_test!
       end
    end
end
```

running rspec is throwing me the following bt:

```
1.1) Failure/Error: example.run

          JSON::GeneratorError:
            source sequence is illegal/malformed utf-8
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:153:in `build_json_payload'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:136:in `add_payload'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:21:in `block in build_request'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:17:in `tap'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:17:in `build_request'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:9:in `submit_request'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:87:in `block in run_test!'
          # ./spec/support/database_cleaner.rb:10:in `block (3 levels) in <top (required)>'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/database_cleaner-1.7.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/database_cleaner-1.7.0/lib/database_cleaner/base.rb:100:in `cleaning'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
          # /Users/---------/.rvm/gems/ruby-2.5.1/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
          # ./spec/support/database_cleaner.rb:9:in `block (2 levels) in <top (required)>'
```

**Comment by ngouy** [comment]
Knowing that `formData ` exists, I hasn't realized it was the only way
https://github.com/domaindrivendev/rswag/issues/53
