### ISSUE TITLE
wrong number of arguments (given 2, expected 0) when running tests

### ISSUE THREAD

**Issue by Kutomore** [rswag/rswag#229]
Hi, so I'm writing my documentation together with the tests on a `Post` model on a `Blog` plugin. It's a prtty basic structure so far, the post has an author, title and content. The author I get from the current User. So far both Index and Show testes are working flawlessly, and I have other tests on other models and plugins, but when I try to run the following schema test.

```ruby
path '/blog/v2/posts' do
    post 'Create a new post in the blog' do
      security [Bearer: ['']]
      tags 'Blog'
      consumes 'application/json'
      description 'Create a new post'
      parameter name: :post, in: :body, required: true, schema: {
          type: :object,
          properties: {
              title: { type: :string, example: 'item title' },
              content: { type: :string, example: 'item content' }
          }
      }
      response '201', 'Post found' do
        schema type: :object,
               properties: {
                   data: {
                       '$ref': '#/definitions/blog_posts_object'
                   }
               }
        let(:Authorization) { authenticated_header(user)["Authorization"] }
        run_test!
      end

      response '401', 'Unauthorized' do
        let(:Authorization) { 'invalid' }
        run_test!
      end
    end
  end
```

I get the following error: 
```
ArgumentError:
       wrong number of arguments (given 2, expected 0)
```

With an huge stack that doesn't tell me anything in particular:

<details><summary>Error Stack</summary>
<p>

```
Failure/Error: example.run
     
     ArgumentError:
       wrong number of arguments (given 2, expected 0)
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/memoized_helpers.rb:298:in `block in let'
     # /usr/local/bundle/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:19:in `submit_request'
     # /usr/local/bundle/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:87:in `block in run_test!'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:348:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:507:in `block in run_owned_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:506:in `each'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:506:in `run_owned_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:593:in `block in run_example_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:592:in `reverse_each'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:592:in `run_example_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:462:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:494:in `run_before_example'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:253:in `block in run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # /usr/local/bundle/gems/rspec-rails-3.8.1/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:373:in `execute_with'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # ./spec/support/database_cleaner.rb:14:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/database_cleaner-1.7.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.7.0/lib/database_cleaner/base.rb:100:in `cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /usr/local/bundle/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/support/database_cleaner.rb:13:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:373:in `execute_with'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:342:in `call'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:607:in `run_around_example_hooks_for'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `map'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `map'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `map'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `map'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `map'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/local/bundle/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
     # /usr/local/bundle/bin/rspec:23:in `load'
     # /usr/local/bundle/bin/rspec:23:in `<top (required)>'
```
</p>
</details>

It's also the same Stack on both tests. Anyone got any Ideas of what might be causing this?

**Comment by jaydorsey** [comment]
You defined a required parameter, `post`, but I don't see a `let(:post) { 'blah' }` to match it in your `response` block. Can you try adding one with JSON that matches the defined schema and see if you get the same error?

**Comment by Tokinh0** [comment]
Hey there !
I'm working with him and already has a ```let(:post){ 'blah' }``` and still gives the wrong number of arguments error.
![image](https://user-images.githubusercontent.com/25869545/69056938-bcf18500-09ef-11ea-812c-005b5c7d2ae7.png)
so... when I run this test I even can get to the binding.pry that I put in controller and I get this error:
![image](https://user-images.githubusercontent.com/25869545/69057225-41dc9e80-09f0-11ea-94f9-b60addebe0b4.png)
I really dont know why this is happening, because in update work's fine and it's almost the same thing:
![image](https://user-images.githubusercontent.com/25869545/69057429-a0a21800-09f0-11ea-9150-b8f46af89018.png)

**Comment by jaydorsey** [comment]
> I really dont know why this is happening, because in update work's fine and it's almost the same thing:

Is there a line number associated with that error? If so, does it comport with the `post 'Create a new post in the blog' do` line?

Can you try two things (separately, rather than making both changes at once):

- Move your `let!(:post) { 'blah' }` line inside of your `response '201' ...`block, rather than before the `post ... do` block
- Changing the name of your `let(:post)` to something else, and redefining the parameter name as well?

**Comment by Kutomore** [comment]
> Is there a line number associated with that error? If so, does it comport with the post 'Create a new post in the blog' do line?

It's the same error I mentioned in the OP, I'll try both of your suggestions and report back.

**Comment by jaydorsey** [comment]
> > Is there a line number associated with that error? If so, does it comport with the post 'Create a new post in the blog' do line?
> 
> It's the same error I mentioned in the OP, I'll try both of your suggestions and report back.

Sounds good. My theory is that `post` DSL method is being called by rspec, when it's trying to memoize `let!(:post)`, hence why you get the argument error. The rswag `post` takes 2 arguments (a summary, and a block)

**Comment by Tokinh0** [comment]
LMFAO, it's was exactly this, your theory is fucking right ! thank you man, you are a fucking genius

**Comment by Kutomore** [comment]
Your theory was spot on, thanks for the help, I probably would never have guessed it.

**Comment by joshed-io** [comment]
Excellent theory, thank you! 😅
