### ISSUE TITLE
fail to build_path when specifiying swagger_doc

### ISSUE THREAD

**Issue by benoittgt** [rswag/rswag#26]
Hello

I have 

``` sh
->swagger $ ls **/* 
mobile/swagger.json v1/swagger.json

mobile:
swagger.json

v1:
swagger.json
```

``` ruby
  config.swagger_docs = {
    'v1/swagger.json' => {
      swagger: '2.0',
      info: {
        title: 'API V1',
        version: 'v1'
      }
    },
    'mobile/swagger.json' => {
      swagger: '2.0',
      info: {
        title: 'mobile API V1',
        version: 'v1'
      }
    }
  }
```

``` ruby
describe 'store mobile API', swagger_doc: 'mobile/swagger.json' do
```

But it returns 

```
     Failure/Error: test_visitor.submit_request!(self, example.metadata)
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/swagger_rails-1.0.0.pre.beta2/lib/swagger_rails/test_visitor.rb:39:in `block in build_path'
     # /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/swagger_rails-1.0.0.pre.beta2/lib/swagger_rails/test_visitor.rb:35:in `tap'
     # /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/swagger_rails-1.0.0.pre.beta2/lib/swagger_rails/test_visitor.rb:35:in `build_path'
     # /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/swagger_rails-1.0.0.pre.beta2/lib/swagger_rails/test_visitor.rb:11:in `submit_request!'
     # /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/swagger_rails-1.0.0.pre.beta2/lib/swagger_rails/rspec/dsl.rb:61:in `block in run_test!'
     # ./spec/spec_helper.rb:30:in `block (3 levels) in <top (required)>'
```

It seems that `SwaggerRails.config` load a default but not the one set in swagger_helper.rb.

``` ruby
[1] pry(#<Class>)> SwaggerRails.config
=> #<SwaggerRails::Configuration:0x007fbfdc2bed98
 @swagger_dir_string="/Users/bti/code/appaloosa/swagger",
 @swagger_docs={"v1/swagger.json"=>{:swagger=>"2.0", :info=>{:title=>"API V1", :version=>"v1"}}}>
```

 I had to add manually `swagger_helper.rb` at the beginning maybe it's part of the problem. I keep digging.

**Comment by benoittgt** [comment]
Ok that's super weird
```ruby
[1] pry(#<Class>)> ::RSpec.configuration.swagger_docs
=> {"v1/swagger.json"=>{:swagger=>"2.0", :info=>{:title=>"API V13 ", :version=>"v1"}},
 "mobile/swagger.json"=>{:swagger=>"2.0", :info=>{:title=>"mobile API V1", :version=>"v1"}}}
[2] pry(#<Class>)> SwaggerRails.config.swagger_docs[metadata[:swagger_doc]]
=> nil
[3] pry(#<Class>)> metadata[:swagger_doc]
=> "mobile/swagger.json"
[4] pry(#<Class>)> SwaggerRails.config.swagger_docs.fetch(metadata[:swagger_doc])
KeyError: key not found: "mobile/swagger.json"
from (pry):4:in `fetch'
[5] pry(#<Class>)> ::RSpec.configuration.swagger_docs["mobile/swagger.json"]
=> {:swagger=>"2.0", :info=>{:title=>"mobile API V1", :version=>"v1"}}
```

**Comment by benoittgt** [comment]
I can access to config threw `::RSpec.configuration.swagger_docs`

``` ruby
::RSpec.configuration.swagger_docs
=> {"v1/swagger.json"=>{:swagger=>"2.0", :info=>{:title=>"API V13 ", :version=>"v1"}},
 "mobile/swagger.json"=>{:swagger=>"2.0", :info=>{:title=>"mobile API V1", :version=>"v1"}}}
```

**Comment by benoittgt** [comment]
By copying `swagger_helper.rb` I've mixed configuration from 2 versions for `swagger_rails`.

I 've updated my version to github master (revision : 1150b9c03047e5f01dacf074017d043d7d52d7b1) do the same like https://github.com/domaindrivendev/swagger_rails/blob/7a01babe01e089c863297218f4cbda40a562a7e7/spec/dummy/config/initializers/swagger_rails.rb and https://github.com/domaindrivendev/swagger_rails/blob/7a01babe01e089c863297218f4cbda40a562a7e7/spec/dummy/spec/swagger_helper.rb

And it's working
