### ISSUE TITLE
Uninitialized constant Rswag when running rails console

### ISSUE THREAD

**Issue by belgoros** [rswag/rswag#261]
When starting the Rails console in another environment:
```ruby
bundle exec rails console -e staging
```
it raises the error:
```
gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant': uninitialized constant Rswag (NameError)
	54: from bin/rails:4:in `<main>'
	53: from /Users/Serguei/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
```
I defined `rswag_api.rb` in `initializers` folder as described in [Dynamic Values for Swagger JSON](https://github.com/rswag/rswag#dynamic-values-for-swagger-json) section:
```rb
Rswag::Api.configure do |c|

  # Specify a root folder where Swagger JSON files are located
  # This is used by the Swagger middleware to serve requests for API descriptions
  # NOTE: If you're using rswag-specs to generate Swagger, you'll need to ensure
  # that it's configured to generate files in the same folder
  c.swagger_root = Rails.root.to_s + '/swagger'

  # Inject a lamda function to alter the returned Swagger prior to serialization
  # The function will have access to the rack env for the current request
  # For example, you could leverage this to dynamically assign the "host" property
  #
  c.swagger_filter = lambda { |swagger, env| swagger['host'] = ENV['SWAGGER_DOCS_HOST'] }
end
```
The Gemfile has `rswag` gems defined as follows:
```yml
group :development, :test do
...
  gem 'rswag-api'
  gem 'rswag-ui'
end
````

**Comment by serghost** [comment]
This is because the gem is registered in the `:development, :test` group

**Comment by belgoros** [comment]
@serghost Exactly as it was [suggested](https://github.com/rswag/rswag#getting-started) in the README. Why is it required when starting the rails console in `staging`?

**Comment by serghost** [comment]
@belgoros read thoroughly: `gem 'rswag-api'` and `gem 'rswag-ui'` specified _outside_ `:development, :test` group. In your code gems are included _within_, so the `Rswag` module is not available in other environments
