### ISSUE TITLE
Validating relative files in $ref schema definition

### ISSUE THREAD

**Issue by spikeheap** [rswag/rswag#270]
Hi :wave:,

I'm trying to port an existing (hand-written) OpenAPI 3.0.1 doc into rswag using 2.2.0. Things have gone well so far, but I'm struggling to get schema validation to work with a local file using `$ref`.

The example test is:

```ruby
response '200', 'success' do
  schema "$ref": "get_move_responses.json#/200"
  
  run_test!
end
```
`get_move_responses.json` lives in `<RAILS_ROOT>/swagger/v1/`.

With a bit of jiggery-pokery from https://github.com/rswag/rswag/issues/268#issuecomment-570533891 this generates the following yaml:

```yaml
      responses:
        '200':
          description: success
          schema:
            "$ref": get_move_responses.json#/200
          content:
            application/vnd.api+json:
              schema:
                "$ref": get_move_responses.json#/200
```

This works _great_ for swagger-ui, and the JSON is loaded (`swagger.yaml` and `get_move_responses.json` sit next to each other in `<RAILS_ROOT>/swagger/v1/` so that makes sense). Swagger UI uses that loaded JSON to populate the model:

<img width="1100" alt="Screenshot 2020-01-03 10 21 43" src="https://user-images.githubusercontent.com/464482/71724373-03783300-2e28-11ea-8204-baec0f514db5.png">

### Expected behaviour
Specifying `schema "$ref": "get_move_responses.json#/200"` loads the JSON file relative to the base path for the swagger spec.

### Actual behaviour
An attempt is made to open `<RAILS_ROOT>/get_move_responses.json`, which fails because the file does not exist:

```
  1) Api::V1::MovesController /moves/{moveId} get success returns a 200 response
     Failure/Error: raise JSON::Schema::ReadFailed.new(pathname.to_s, :file)

     JSON::Schema::ReadFailed:
       Read of file at /Users/rb/src/test_rswag_error/get_move_responses.json failed
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/schema/reader.rb:136:in `rescue in read_file'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/schema/reader.rb:129:in `read_file'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rswag-specs-2.2.0/lib/rswag/specs/response_validator.rb:12:in `read'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/validator.rb:142:in `load_ref_schema'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/validator.rb:153:in `build_schemas'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/validator.rb:56:in `block in initialize'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/validator.rb:56:in `synchronize'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/validator.rb:56:in `initialize'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/validator.rb:255:in `new'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/validator.rb:255:in `validate!'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/validator.rb:273:in `fully_validate'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rswag-specs-2.2.0/lib/rswag/specs/response_validator.rb:64:in `validate_body!'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rswag-specs-2.2.0/lib/rswag/specs/response_validator.rb:34:in `validate!'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rswag-specs-2.2.0/lib/rswag/specs/example_helpers.rb:31:in `assert_response_matches_metadata'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rswag-specs-2.2.0/lib/rswag/specs/example_group_helpers.rb:91:in `block in run_test!'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:257:in `instance_exec'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:257:in `block in run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/hooks.rb:464:in `block in run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:345:in `call'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-rails-3.8.2/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:450:in `instance_exec'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:450:in `instance_exec'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/hooks.rb:373:in `execute_with'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:345:in `call'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/hooks.rb:607:in `run_around_example_hooks_for'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/hooks.rb:464:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:254:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:629:in `map'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:629:in `run_examples'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:595:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:596:in `block in run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:596:in `map'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:596:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:596:in `block in run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:596:in `map'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:596:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:596:in `block in run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:596:in `map'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:596:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:116:in `map'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/configuration.rb:2008:in `with_suite_hooks'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:110:in `run_specs'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:87:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:71:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/exe/rspec:4:in `<top (required)>'
     # /usr/local/opt/rbenv/versions/2.6.2/bin/rspec:23:in `load'
     # /usr/local/opt/rbenv/versions/2.6.2/bin/rspec:23:in `<top (required)>'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
     # /usr/local/opt/rbenv/versions/2.6.2/bin/bundle:23:in `load'
     # /usr/local/opt/rbenv/versions/2.6.2/bin/bundle:23:in `<main>'
     #
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
     # ------------------
     # --- Caused by: ---
     # Errno::ENOENT:
     #   No such file or directory @ rb_sysopen - /Users/rb/src/test_rswag_error/get_move_responses.json
     #   /usr/local/Cellar/rbenv/1.1.2/versions/2.6.2/lib/ruby/gems/2.6.0/gems/json-schema-2.8.1/lib/json-schema/schema/reader.rb:131:in `read'
```

I'm reluctant to work around this by loading the JSON explicitly in the definition section within `swagger_helper.rb` and then referencing them internally if I can help it, just because I'm trying to minimise the changes to the codebase while the team tests out the new approach.

I've had a bit of a dig into the schema loader, and I can't see a way to set the base path when calling `JSON::Validator.fully_validate`, but I'm probably missing something!

**Comment by BookOfGreg** [comment]
Hey @spikeheap did you ever get this working? I see there was some work at the MOJ on this, would always love some help, esp from a group with such a good reputation in UK tech.

**Comment by spikeheap** [comment]
Hi @BookOfGreg, sorry for the slow reply. Your question coincided with becoming a parent, so I've been avoiding GitHub for a bit 😄.

Unfortunately I moved to another team not long after filing this issue, and since then the RSwag DSL has been removed from that project's tests :(. Sorry I don't have better news!
