### ISSUE TITLE
Rspec disable_monkeypatching and minitest interaction

### ISSUE THREAD

**Issue by sergioisidoro** [rswag/rswag#279]
Hi there! 
First of all, great work, and thank you you making this possible. 

About our issue: We're a bit in a strange position where we're running both minitest and rspec (large amount of tests, impossible to migrate all at once, and we're currently debating the future of our testing framework). 

Rspec and Minitest seem to work in friendly terms off the shelf while using `disable_monkey_patching!` which seems to work. However, as soon as we load rswag gem the whole setup stops working and we have not been able to find out why. 

It seems that as soon as rswag is loaded, the minitest function`test` and some others gets unset, leading to failure of our minitest set. I'm wondering if this is a result of not supporting `disable_monkey_patching`. 

Could someone point us in the right direction, or advise how could we contribute to improve this situation.

Thanks 👍

**Comment by BookOfGreg** [comment]
That's interesting. Can you provide an example of forbidden monkeypatching that I can use to test if we're breaking the rules or not?
In my companies projects we do use both minitest and rspec/rswag too, but we don't get the behavior you describe so if I have an example that would help me narrow it down greatly.

**Comment by sergioisidoro** [comment]
Ok, so to replicate the issue here's what I done (I will upload and link to the repo bellow):
Create a clean rails project, with the following additional gems in the `:development, :test` group:
```
#   gem "rspec-rails"
#   gem 'rswag-specs'
  gem "minitest"
  gem "minitest-rails"
  gem 'minitest-reporters'
```

Add the following test 
```
# encoding: utf-8
require 'test_helper'

class TheTest < ActiveSupport::TestCase
    describe "strange_mix" do
        test "the truth" do
            assert true
        end
    end
end

describe "plain minitest spec" do
    it "the other truth" do
      assert true
    end
end
```
When I run it with the commented gems I get the result:
```
Run options: --seed 20106

# Running:

..

Finished in 0.004066s, 491.8839 runs/s, 491.8839 assertions/s.
```

If I uncomment the `gem 'rspec-rails'` and run the rake to install the helpers and configs, everything works fine and I still get the same result.

But if I uncomment `gem 'rswag-specs'` then I get:

```
/Users/sergio/Development/thingamabob/test/models/test_test.rb:6:in `test': unknown command 't' (ArgumentError)                                                                                             
        from /Users/sergio/Development/thingamabob/test/models/test_test.rb:6:in `block in <class:TheTest>'                                                                                                 
        from /Users/sergio/.rvm/gems/ruby-2.4.6/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:387:in `module_exec'                                                                                  
        from /Users/sergio/.rvm/gems/ruby-2.4.6/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:387:in `subclass'                                                                                     
        from /Users/sergio/.rvm/gems/ruby-2.4.6/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'                                                         
        from /Users/sergio/.rvm/gems/ruby-2.4.6/gems/rspec-core-3.9.0/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'                                                                     
        from /Users/sergio/.rvm/gems/ruby-2.4.6/gems/rspec-core-3.9.0/lib/rspec/core/dsl.rb:84:in `block (2 levels) in expose_example_group_alias_globally'      
....
```

**Comment by sergioisidoro** [comment]
Here's the repo with the replicated issue:
https://github.com/sergioisidoro/rails-project-sandbox

To replicate the situation we just need to de-comment that line 43 of the Gemfile
https://github.com/sergioisidoro/rails-project-sandbox/blob/master/Gemfile#L43

Note: This can also be me doing something extremely wrong. And thank you for taking the time to help out :)

**Comment by sergioisidoro** [comment]
Also, with all gems setup (minitest + rspec + rswag), and if I remove that strange hybrid of minitest/spec, leaving only the second test, everything gets evaluated but no assertions are made.

`test_test.rb`
```
require 'test_helper'

describe "plain minitest spec" do
    it "the other truth" do
      assert true
    end
end
```

```

# Running:

Finished in 0.002407s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

But as soon as I comment `rswag` again, it runs and assertions are made.

```

# Running:

.

Finished in 0.002506s, 399.0423 runs/s, 399.0423 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by sergioisidoro** [comment]
So, I've navigated a bit on the repo, and I'm wondering if the loading of rspec/core here could be the reason: https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs.rb#L1

This issue https://github.com/rspec/rspec-core/issues/2301 may lead to the answer, and some linked issues should provide some light on loading rspec-core: https://github.com/rspec/rspec-rails/pull/1678

I'm not sure how to help here.

**Comment by sergioisidoro** [comment]
Managed to bypass the issue by using   
`gem "rswag-specs", require: false` 

and by doing 

`require "rswag/specs"` 
in `spec/rails_helper.rb` right after loading `require 'rspec/rails'`

I'm not sure if there's any way of not loading rspec-core, and this is a bit of an edge case, so maybe not worth the effort to refactor.

But at least I could add some documentation for people who might struggle with this issue.

**Edit:** This has the nasty side effect. I need to remove the `require: false` from gemfile everytime I need to run `rake rswag:specs:swaggerize`

**Comment by salzig** [comment]
Same problem here, but we only use minitest for our testsuite, so rswag is the only one introducing the rspec dependency - which then kills our minitest suite. 

I also had the idea of using `require: false`, but ended up with the same problem of killing thereby the rake task.

**Comment by nijicha** [comment]
For the side effect, I had found a way to fix

1 . Just add `require 'rswag/specs'` into Rakefile

```ruby
# Rakefile

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

require 'rswag/specs' # <-- Add this line

Rails.application.load_tasks
```

2. Reload hierarchy of rake tasks by

```bash
rake --tasks
```

So rswag won't be initiated as required dependencies for Rails app
But load in 
- `spec/rails_helper.rb` for specs
- `Rakefile` for rake tasks

**Comment by andre-bare** [comment]
I too, have the issue of rswag disabling the minitest spec style tests. 
Merely putting require 'rswag/specs' in the Rakefile is sufficient for triggering it. 

Specifically: I only use minitests for my tests. For the test using test syntax, there are no issues. For tests using the Minitest spec syntax (describe Object do), these spec tests are silently skipped as mentioned above (and I do not have any rspec tests other  than the rswag ones). These minitest spec tests are skipped whenever I include rswag/specs, even if only in the rakefile. (Note:   rspec-rails itself is always included)

My solution:
``` ruby
# Gemfile:
gem "rspec-rails" #Mandated by rswag-specs, otherwise unused
gem "rswag-specs", require: false  # <-- do not load by default
```
```ruby
# Rakefile
# Standard Rakefile, no addition
```
```ruby
# Rakefile-rswag
# Separate rakefile to include rswag/specs
require_relative 'config/application'
require 'rswag/specs' # <-- Add this line
Rails.application.load_tasks
```
```ruby
# swagger_helper.rb
require 'rails_helper'
require 'rswag/specs'  # <--  add this line

```

Generate the rswagger file with 
```shell
rake -f Rakefile-rswag rswag:specs:swaggerize
```

I tried loading the rswag/spec in the Rakefile only for the rswag task, but my Rakefile knowledge was too limited to work around invoking a rake task (rswag) that wasn't initially available

**Comment by sergioisidoro** [comment]
Not stale

**Comment by emptyflask** [comment]
I was just looking at using rswag, but maintain a number of projects that only use minitest (and I like it that way...), so this issue is critical for me.

**Comment by NeilSlater-Clixifix** [comment]
Also had this issue recently. We're looking at retiring Minitest in favour of `rspec` as the only test suite in our repo, but with 800 legacy tests this will take time. 

I used [andre-bare](https://github.com/andre-bare)'s solution above and it is fine as a work-around to have a more complicated Swagger-generating command. You could equally have a `Rakefile-minitest` file for running legacy test suite without the require.
