### ISSUE TITLE
rswag-api crashes the rails with unknown firstpos: NilClass error

### ISSUE THREAD

**Issue by thg303** [rswag/rswag#313]
simply followed the documentation. I tried commenting out the mount line at `config/routes.rb`, commented all initializer file `rswag-api.rb` still no change. the error was gone when I removed the gem from Gemfile.
`rails v5.1`
`ruby v2.5.0`

full stack trace:
```
2020-05-04 13:46:49.839730 F [9649:puma 001 debug_exceptions.rb:9] Rails -- Exception: ArgumentError: unknown firstpos: NilClass
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/gtg/builder.rb:99:in `firstpos'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/gtg/builder.rb:22:in `transition_table'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/routes.rb:58:in `simulator'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:97:in `simulator'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:28:in `eager_load!'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:394:in `eager_load!'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:26:in `each'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:26:in `execute'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/application/finisher.rb:141:in `block (2 levels) in <module:Finisher>'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `instance_exec'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:600:in `catch'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:600:in `block in default_terminator'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:198:in `block in halting'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `each'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `invoke_before'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:130:in `run_callbacks'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/execution_wrapper.rb:108:in `run!'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/reloader.rb:113:in `run!'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/execution_wrapper.rb:70:in `block in run!'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/execution_wrapper.rb:67:in `tap'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/execution_wrapper.rb:67:in `run!'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/reloader.rb:59:in `run!'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:10:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/web-console-3.6.2/lib/web_console/middleware.rb:135:in `call_app'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/web-console-3.6.2/lib/web_console/middleware.rb:30:in `block in call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/web-console-3.6.2/lib/web_console/middleware.rb:20:in `catch'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/web-console-3.6.2/lib/web_console/middleware.rb:20:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rails_semantic_logger-4.4.3/lib/rails_semantic_logger/rack/logger.rb:43:in `call_app'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rails_semantic_logger-4.4.3/lib/rails_semantic_logger/rack/logger.rb:28:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/static.rb:125:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sentry-raven-2.9.0/lib/raven/integrations/rack.rb:51:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
/Users/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by mathieujobin** [comment]
I did not get this problem but I would suggest you to try two things.
* grep your own code and gems for `firstpos` I am not seeing this in rswag gem
* try the same thing in an empty application, just to isolate you don't have an extra setting getting in the way.

**Comment by jtannas** [comment]
This seems to be a Rails issue and not an RSwag issue
- https://stackoverflow.com/questions/44465118/rails-5-1-unknown-firstpos-nilclass-issue-reloading-application
- https://github.com/rails/rails/pull/32296
- https://github.com/rails/rails/pull/33118

Closing this issue because of it. If you're still running into problems though and are sure it's an RSwag issue, feel free to open up another issue and we'll take a look at it.
Cheers 🙂
