### ISSUE TITLE
readOnly and writeOnly not supported?

### ISSUE THREAD

**Issue by tmaier** [rswag/rswag#336]
Properties with `writeOnly` are only relevant for requests altering the object.
Properties with `readOnly` are only relevant for requests being read.

`writeOnly: true` leads to the following error:

```text
  1) Api::V1::UsersController /users/{id} get user found returns a 200 response
     Failure/Error: raise UnexpectedResponse, "Expected response body to match schema: #{errors[0]}" if errors.any?

     Rswag::Specs::UnexpectedResponse:
       Expected response body to match schema: The property '#/' did not contain a required property of 'password' in schema ac2d10ca-51aa-5a64-bc50-a5414a678e6a#
     # /usr/local/bundle/gems/rswag-specs-2.3.1/lib/rswag/specs/response_validator.rb:53:in `validate_body!'
     # /usr/local/bundle/gems/rswag-specs-2.3.1/lib/rswag/specs/response_validator.rb:20:in `validate!'
     # /usr/local/bundle/gems/rswag-specs-2.3.1/lib/rswag/specs/example_helpers.rb:30:in `assert_response_matches_metadata'
     # /usr/local/bundle/gems/rswag-specs-2.3.1/lib/rswag/specs/example_group_helpers.rb:95:in `block in run_test!'
```

**Comment by tmaier** [comment]
still relevant, if you want to fully support OpenApi 3.0

**Comment by jrub** [comment]
I've used Rswag to document our API and found duplicating some schemas on one for the request and one for the response. They're similar but slightly different.  

I'd love to use these properties for specifying these differences, it'd help removing duplication. In case it helps, I like how bump.sh is doing it: https://docs.bump.sh/help/specifications-support/openapi-support/#readonly-and-writeonly-properties

I'd be nice to keep this issue open and trying to accomplish a similar solution.

**Comment by jrub** [comment]
This would be very nice to have to avoid having one schema for the request and another for the response.

**Comment by romanblanco** [comment]
Marking this as a dupliacate of https://github.com/rswag/rswag/issues/160

**Comment by lavoscore** [comment]
Any prospect of this being implemented? It's a shame having to duplicate schemas. 

My workaround to DRY myself out of this has been to isolate common properties in base schemas. Something like:

```ruby
# under components -> schemas
post: {
  type: :object,
  properties: {
    # properties common to both request and response
    title: { type: :string },
    content: { type: :string },
    # ...
  }
},

post_request: {
  'allOf': [
    { '$ref': '#/components/schemas/post' },
    {
       type: :object,
       properties: {
         author_id: { type: :integer }
       },
       required: %w[author_id]
    }
  ]
}.

post_response: {
  'allOf': [
    { '$ref': '#/components/schemas/post' },
    {
       type: :object,
       properties: {
         id: { type: :integer },
         author: { '$ref': '#/components/schemas/author_response' },
       },
       required: %w[id author]
     }
  ]
}
```

**Comment by jrub** [comment]
Any news on how to avoid duplicating schemas? Thanks!
