### ISSUE TITLE
rswag generates invalid urls with Umlauts in a parameter

### ISSUE THREAD

**Issue by tmaier** [rswag/rswag#381]
```
     3.1) Failure/Error: raise InvalidURIError, "URI must be ascii only #{uri.dump}"

          URI::InvalidURIError:
            URI must be ascii only "http://customer-816.example.com:80/api/v1/publications?page=1&per_page=1&query=Haus ohne H\u00FCter&starred_by=&f=true&author=&category=&editor=&entry_type=&issn=&journal=&language=&md5=&organization=&series=&with_assets=&year="
          # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:214:in `parse_uri'
          # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:117:in `request'
          # /usr/local/bundle/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
          # /usr/local/bundle/gems/rswag-specs-2.3.1/lib/rswag/specs/example_helpers.rb:20:in `submit_request'
          # /usr/local/bundle/gems/rswag-specs-2.3.1/lib/rswag/specs/example_group_helpers.rb:91:in `block in run_test!'
```

The paramter `query` is generated by the faker gem with a german language string, which may contain non-ascii characters, like umlauts.

Please consider to `CGI.escape` the parameters for the tests

**Comment by tmaier** [comment]
I do the following now in my tests

```ruby
    let(:query) { CGI.escape('Lorem ipsum') }
    # ...
        run_test! do
          data = JSON.parse(response.body)

          expect(data.dig('records', 0, 'abstract')).to eq('Lorem ipsum')
        end
```

**Comment by jtannas** [comment]
heyo - this is an issue with `rack-test` that I've been meaning to put a PR in for a few months now 😅 
https://github.com/rack/rack-test/issues/266

If you'd like to jump on it instead I'd really appreciate it 🙇

**Comment by tmaier** [comment]
So I checked https://github.com/rack/rack-test/issues/266 again. It states basically, that this must be fixed in rswag, not rack-test. The input must be escaped beforehand.

So it would be great, if this could be handled in rswag.

**Comment by tmaier** [comment]
ping. still relevant.
