### ISSUE TITLE
Cannot generate documentation

### ISSUE THREAD

**Issue by coding-red-panda** [rswag/rswag#452]
I'm receiving the following output when running the command `rake rswag:specs:swaggerize`

```
/Users/olivar/.rbenv/versions/2.7.3/bin/ruby -I/Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib:/Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-support-3.10.2/lib /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
Generating Swagger docs ...
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Traceback (most recent call last):
        16: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
        15: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
        14: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
        13: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
        12: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
        11: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:76:in `report'
        10: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:174:in `finish'
         9: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:194:in `close_after'
         8: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:175:in `block in finish'
         7: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:202:in `stop'
         6: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:208:in `notify'
         5: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:208:in `each'
         4: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:209:in `block in notify'
         3: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:52:in `stop'
         2: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:52:in `each'
         1: from /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:75:in `block in stop'
/Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:75:in `join': no implicit conversion of Symbol into String (TypeError)
/Users/olivar/.rbenv/versions/2.7.3/bin/ruby -I/Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib:/Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-support-3.10.2/lib /Users/olivar/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined failed
```

From the stacktrace I'm assuming the code doesn't like some kind of definition somewhere, but I'm unable to pinpoint what exactly it doesn't like. Running `bundle exec rspec` makes all tests pass.

This is the integration test we added:

```
# frozen_string_literal: true

# This integration spec is responsible for generating the required documentation with the RSwag gem,
# that allows us to document the API of the Deployment History Application.
# By running the specs, all information about requests is collected and documented.
require 'swagger_helper'

describe 'Deployments API' do
  path '/api/v1/deployments/{id}' do
    get 'Retrieves a Deployment' do
      tags 'Deployments'
      security [bearer_auth: []]
      produces 'application/json'
      parameter name: :id, in: :path, type: :string

      response '200', 'deployment found' do
        schema type: :object,
               properties: {
                 id: { type: :integer },
                 application_name: { type: :string },
                 version: { type: :string },
                 branch: { type: :string },
                 host: { type: :string },
                 deployed_at: { type: :string },
                 deployed_by: { type: :string },
                 environment: { type: :string },
                 deployment_id: { type: :integer, nullable: true },
                 application_id: { type: :integer },
                 created_at: { type: :string },
                 updated_at: { type: :string }
               },
               required: %i[
                 id
                 application_name
                 version
                 branch
                 host
                 deployed_at
                 deployed_by
                 environment
                 created_at
                 updated_at
               ]

        let(:id) { create(:deployment, host: 'example.com').id }
        let(:Authorization) { ::ActionController::HttpAuthentication::Token.encode_credentials(token) }
        let(:token) { ::ENV['TOKEN'] }
        run_test!
      end

      response '401', 'Request unauthorized' do
        let(:id) { create(:deployment, host: 'example.com').id }
        let(:Authorization) { ::ActionController::HttpAuthentication::Token.encode_credentials(token) }
        let(:token) { 'bogus' }
        run_test!
      end

      response '404', 'Deployment not found' do
        let(:id) { 'invalid' }
        let(:Authorization) { ::ActionController::HttpAuthentication::Token.encode_credentials(token) }
        let(:token) { ::ENV['TOKEN'] }
        run_test!
      end
    end
  end

  path '/api/v1/deployments' do
    post 'Creates a Deployment' do
      tags 'Deployments'
      security [bearer_auth: []]
      consumes 'application/json'

      parameter name: :deployment, in: :body, schema: {
        type: :object,
        properties: {
          application: { type: :string },
          branch: { type: :string },
          version: { type: :string },
          deployed_by: { type: :string },
          host: { type: :string }
        },
        require: [:application, :branch, :version, :deployed_by, :host]
      }

      response '201', 'Deployment created' do
        let(:deployment) do
          {
            application: 'myApp',
            branch: 'master',
            version: '35vdg56',
            deployed_by: 'Me',
            host: 'example.com'
          }
        end
        let(:Authorization) { ::ActionController::HttpAuthentication::Token.encode_credentials(token) }
        let(:token) { ::ENV['TOKEN'] }
        run_test!
      end
    end
  end
end

```

**Comment by coding-red-panda** [comment]
Fixed the problem.
Swagger explicitly expects a string for it's documentation key in the schema definition.
So used `.with_indifferent_access` since we write all Hashes with symbols in our project.
