### ISSUE TITLE
Cannot generate documentation (cannot load such file -- rails_helper)

### ISSUE THREAD

**Issue by alexohneander** [rswag/rswag#456]
**Rails**: 6.1.4.1
**Ruby**: 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

I cannot run the command to create the documentations.
Can anyone do anything with the error? I am not getting anywhere here.

The project is freshly set up and is an API project with 2 controllers.

`rake rswag:specs:swaggerize`
```bash
/Users/alex/.rvm/rubies/ruby-3.0.0/bin/ruby -I/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib:/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-support-3.10.2/lib /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
No examples found.
/Users/alex/Projects/Ruby/lan_house/ms_house_api/spec/swagger_helper.rb:3:in `require': cannot load such file -- rails_helper (LoadError)
	from /Users/alex/Projects/Ruby/lan_house/ms_house_api/spec/swagger_helper.rb:3:in `<top (required)>'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:5:in `require'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rswag-specs-2.4.0/lib/rswag/specs/swagger_formatter.rb:5:in `<top (required)>'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:235:in `require'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:235:in `rescue in custom_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:232:in `custom_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:183:in `find_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:152:in `add'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:974:in `add_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `block in load_formatters_into'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `each'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `load_formatters_into'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:24:in `configure'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:132:in `configure'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `block in custom_formatter': uninitialized constant Rswag (NameError)
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `each'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `inject'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:233:in `custom_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:183:in `find_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters.rb:152:in `add'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:974:in `add_formatter'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `block in load_formatters_into'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `each'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:118:in `load_formatters_into'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:24:in `configure'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:132:in `configure'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
/Users/alex/.rvm/rubies/ruby-3.0.0/bin/ruby -I/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/lib:/Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-support-3.10.2/lib /Users/alex/.rvm/gems/ruby-3.0.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined failed
```

**Gemfile**
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
# Use Puma as the app server
gem 'puma', '~> 5.0'

# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use CockroachDB as the database
gem 'activerecord-cockroachdb-adapter', '~> 6.1.0'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.9.1', require: false

# Use rswag for API documentation
gem 'rswag'
gem 'rspec-core'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by PhilT** [comment]
You might need `gem 'rspec-rails'` (rather than `rspec-core`) and then run `rails g rspec:install`

**Comment by moritonal** [comment]
The whole intro process for this gem is rough. If I create a new ruby project, and follow the readme this is one of about four issues I hit. 

You also have to have `SWAGGER_DRY_RUN=0 RAISL_ENV=test rake rswag:specs:swaggerize` to even have it consider your models, and even then it still outputs nothing. I'll try work out an actual update to the README to make this work.

EDIT: Okay... a few hours later and knee-deep in integration rspecs, I realise what I've been missing, but do have to really ask that you reconsider the word "seemless" in the description. For a project that doesn't already use rspec in earnest, it entails a vast amount of work. It's not your fault that you're the first hit when searching for Ruby & Swagger, but the effect is the same.

**Comment by jtannas** [comment]
Hi @moritonal - sorry about that.
This gem sat fairly unmaintained for a long time. There's now a new group of maintainers getting set up, but it's going to take us awhile to catch up with all the accumulated issues.
If you're interested in helping out, I'd welcome a PR to help clean up the ReadMe. We're also experimenting with using the [wiki](https://github.com/rswag/rswag/wiki) for examples.
