### ISSUE TITLE
Error on specs with multiple responses with same return code defined

### ISSUE THREAD

**Issue by mdesantis80** [rswag/rswag#52]
Hi,

while testing APIs it can happen you'll have the same HTTP response code for different reasons, like for example running the following spec:

```
require 'swagger_helper'

describe 'Test my API'

  path '/api/document' do

    post 'Creates a new document' do
      
      parameter name: :document, in: :body, required: true, schema: {
        title:  {  type: :string  },
        text:  {  type: :string  },
        required: ['title','text']
      }

      response '200', 'Login OK' do        
        let!(:document) {
          {
          	"title" => "My document",
            "text" => "Lorem ipsum dolor"            
          }
        }
        run_test!
      end

      response '422', 'No title provided' do
        let!(:document) {
          {          
            "text" => "Lorem ipsum dolor"            
          }
        }
        run_test!
      end

      response '422', 'No text provided' do
        let!(:document) {
          {          
            "title" => "My document"
          }
        }
        run_test!
      end                              

    end

  end

end
```

yields the following error:

```
<ruby_root>.rvm/gems/ruby-2.2.2/gems/rswag-specs-1.2.1/lib/rswag/specs/example_group_helpers.rb:50:in `response': wrong number of arguments (1 for 2) (ArgumentError)
	from <ruby_root>workspaces/mobile_server/spec/integration/social_login_spec.rb:80:in `block (3 levels) in <top (required)>'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `module_exec'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `subclass'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rswag-specs-1.2.1/lib/rswag/specs/example_group_helpers.rb:13:in `block (2 levels) in <module:ExampleGroupHelpers>'
	from <ruby_root>workspaces/mobile_server/spec/integration/social_login_spec.rb:40:in `block (2 levels) in <top (required)>'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `module_exec'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `subclass'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rswag-specs-1.2.1/lib/rswag/specs/example_group_helpers.rb:7:in `path'
	from <ruby_root>workspaces/mobile_server/spec/integration/social_login_spec.rb:38:in `block in <top (required)>'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `module_exec'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `subclass'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/dsl.rb:84:in `block (2 levels) in expose_example_group_alias_globally'
	from <ruby_root>workspaces/mobile_server/spec/integration/social_login_spec.rb:36:in `<top (required)>'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from <ruby_root>.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from <ruby_root>.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
	from <ruby_root>.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
	from <ruby_root>.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from <ruby_root>.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

I'm using version 1.2.1 and would love to keep  generating swagger files with rswag!

If this can help, version 1.2.0 was not throwing exception, but the generated swagger only had one section per response with the same HTTP code (the last defined one).

**Comment by domaindrivendev** [comment]
Hey there. Thanks for the feedback. However, I'm unable to reproduce the exception with 1.2.1. I've copied in the exact spec you've provided above and everything appears to work well ...

<img width="998" alt="screen shot 2017-04-12 at 10 44 24 pm" src="https://cloud.githubusercontent.com/assets/1434343/24991771/2cf41b48-1fd2-11e7-8b69-0be0efb3f09a.png">

Secondly, the [Swagger specification](http://swagger.io/specification/) only allows for one response description per response code. So, rswag picks the last one. Given that non-adherence to the spec is not an option, what else would you propose it does?

**Comment by mdesantis80** [comment]
I propose to close this issue :)
I fixed my code and for sure we don't want to generate something out of spec.
Thanks for getting back anyway!
