### ISSUE TITLE
[BUG] (Maybe) `request_body_example`method in example_group_helpers.rb is not appear in my local gem.

### ISSUE THREAD

**Issue by TOSUKUi** [rswag/rswag#569]
## Describe the bug
※Maybe specific on my environment.

Show error messages in below.

run `bundle exec rake rswag:specs:swaggerize` command, then,
```
Generating Swagger docs ...

An error occurred while loading ./spec/requests/{hoge}_spec.rb.
Failure/Error: request_body_example value: { id: 1 }, name: 'normal', summary: 'normal request example'

NoMethodError:
  undefined method `request_body_example' for RSpec::ExampleGroups::FooBar::FooBar::Get:Class
  Did you mean?  require_or_load
# ./spec/requests/{hoge}_spec.rb:26:in `block (3 levels) in <main>'
# ./spec/requests/{hoge}_spec.rb:21:in `block (2 levels) in <main>'
# ./spec/requests/{hoge}_spec.rb:20:in `block in <main>'
# ./spec/requests/{hoge}_spec.rb:3:in `<main>'
Swagger doc generated at path/{hoge}/swagger/v1/swagger.yaml
```

I lost my code so paste the example code from README.md.

It should be occurred in this code.
```ruby
path '/blogs/{id}' do

    get 'Retrieves a blog' do
      tags 'Blogs', 'Another Tag'
      produces 'application/json', 'application/xml'
      parameter name: :id, in: :path, type: :string
      request_body_example value: { some_field: 'Foo' }, name: 'basic', summary: 'Request example description'

      response '200', 'blog found' do
        schema type: :object,
          properties: {
            id: { type: :integer },
            title: { type: :string },
            content: { type: :string }
          },
          required: [ 'id', 'title', 'content' ]

        let(:id) { Blog.create(title: 'foo', content: 'bar').id }
        run_test!
      end
```

## Expected behavior
request_body_example can be called  in {hoge}_spec.rb

## Version
Rswag-spec version is 2.6.0 but it also occurred on 2.7.0.

According my  research, the source codes are different between Github repository and my local gem files.

I would show the code of `exapmle_group_helpers.rb` on my gem below.

As you can see,  request_body_example is not appear in this code, but it appear in this remote repository.
```ruby
# frozen_string_literal: true

module Rswag
  module Specs
    module ExampleGroupHelpers
      def path(template, metadata = {}, &block)
        metadata[:path_item] = { template: template }
        describe(template, metadata, &block)
      end

      [:get, :post, :patch, :put, :delete, :head, :options, :trace].each do |verb|
        define_method(verb) do |summary, &block|
          api_metadata = { operation: { verb: verb, summary: summary } }
          describe(verb, api_metadata, &block)
        end
      end

      [:operationId, :deprecated, :security].each do |attr_name|
        define_method(attr_name) do |value|
          metadata[:operation][attr_name] = value
        end
      end

      # NOTE: 'description' requires special treatment because ExampleGroup already
      # defines a method with that name. Provide an override that supports the existing
      # functionality while also setting the appropriate metadata if applicable
      def description(value = nil)
        return super() if value.nil?

        metadata[:operation][:description] = value
      end

      # These are array properties - note the splat operator
      [:tags, :consumes, :produces, :schemes].each do |attr_name|
        define_method(attr_name) do |*value|
          metadata[:operation][attr_name] = value
        end
      end

      def parameter(attributes)
        if attributes[:in] && attributes[:in].to_sym == :path
          attributes[:required] = true
        end

        if metadata.key?(:operation)
          metadata[:operation][:parameters] ||= []
          metadata[:operation][:parameters] << attributes
        else
          metadata[:path_item][:parameters] ||= []
          metadata[:path_item][:parameters] << attributes
        end
      end

      def response(code, description, metadata = {}, &block)
        metadata[:response] = { code: code, description: description }
        context(description, metadata, &block)
      end

      def schema(value)
        metadata[:response][:schema] = value
      end

      def header(name, attributes)
        metadata[:response][:headers] ||= {}

        metadata[:response][:headers][name] = attributes
      end

      # NOTE: Similar to 'description', 'examples' need to handle the case when
      # being invoked with no params to avoid overriding 'examples' method of
      # rspec-core ExampleGroup
      def examples(examples = nil)
        return super() if examples.nil?
        # should we add a deprecation warning?
        examples.each_with_index do |(mime, example_object), index|
          example(mime, "example_#{index}", example_object)
        end
      end

      def example(mime, name, value, summary=nil, description=nil)
        # Todo - move initialization of metadata somewhere else.
        if metadata[:response][:content].blank?
          metadata[:response][:content] = {}
        end

        if metadata[:response][:content][mime].blank?
          metadata[:response][:content][mime] = {}
          metadata[:response][:content][mime][:examples] = {}
        end

        example_object = {
          value: value,
          summary: summary,
          description: description
        }.select { |_, v| v.present? }
        # TODO, issue a warning if example is being overridden with the same key
        metadata[:response][:content][mime][:examples].merge!(
          { name.to_sym => example_object }
        )
      end

      def run_test!(&block)
        # NOTE: rspec 2.x support
        if RSPEC_VERSION < 3
          before do
            submit_request(example.metadata)
          end

          it "returns a #{metadata[:response][:code]} response", rswag: true do
            assert_response_matches_metadata(metadata)
            block.call(response) if block_given?
          end
        else
          before do |example|
            submit_request(example.metadata)
          end

          it "returns a #{metadata[:response][:code]} response", rswag: true do |example|
            assert_response_matches_metadata(example.metadata, &block)
            example.instance_exec(response, &block) if block_given?
          end
        end
      end
    end
  end
end
```

## Steps to Test or Reproduce
Please provide an example repo or the steps to reproduce the behavior.

## Rswag Version
2.7.0 but also occured in 2.6.0 .

## Relates to which version of OAS (Open API Specification)
- [ ] OAS2
- [ ] OAS3
- [x] OAS3.1

**Comment by romanblanco** [comment]
@TOSUKUi, this is because the changes adding `request_body_example` method were not released yet.

2.6.0 version has been released on 9th of September, before the PR adding `request_body_example` (https://github.com/rswag/rswag/pull/555) has been merged.

The changes aren't even listed for 2.7.0 release yet (https://github.com/rswag/rswag/discussions/561), so this might get released in 2.8.0.

**Comment by TOSUKUi** [comment]
Thanks for respond.
That make sense.

**Comment by harlantwood** [comment]
I am using this feature by loading the gem from github with the following entry in my `Gemfile`:

```rb
  gem "rswag-specs", git: "https://github.com/rswag/rswag.git", branch: "master", 
    glob: "rswag-specs/rswag-specs.gemspec" # to get request examples, merged in https://github.com/rswag/rswag/pull/555
```
