### ISSUE TITLE
[BUG] Cannot load rails_helper

### ISSUE THREAD

**Issue by philsturgeon** [rswag/rswag#719]
## Describe the bug

Following the README instructions on a clear project produces these errors when I try to generate OpenAPI regardless of how I run the command:

```
bin/rake rswag:specs:swaggerize
/Users/phil/.asdf/installs/ruby/2.7.0/bin/ruby -I/Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib:/Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-support-3.12.1/lib /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
No examples found.
Traceback (most recent call last):
	16: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<main>'
	15: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
	14: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
	13: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:86:in `run'
	12: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:99:in `setup'
	11: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:132:in `configure'
	10: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:24:in `configure'
	 9: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:118:in `load_formatters_into'
	 8: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:118:in `each'
	 7: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:118:in `block in load_formatters_into'
	 6: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:976:in `add_formatter'
	 5: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:152:in `add'
	 4: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:183:in `find_formatter'
	 3: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:239:in `custom_formatter'
	 2: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:239:in `inject'
	 1: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:239:in `each'
/Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:239:in `block in custom_formatter': uninitialized constant Rswag (NameError)
	19: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<main>'
	18: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
	17: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
	16: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:86:in `run'
	15: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:99:in `setup'
	14: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:132:in `configure'
	13: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:24:in `configure'
	12: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:118:in `load_formatters_into'
	11: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:118:in `each'
	10: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:118:in `block in load_formatters_into'
	 9: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:976:in `add_formatter'
	 8: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:152:in `add'
	 7: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:183:in `find_formatter'
	 6: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:238:in `custom_formatter'
	 5: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:241:in `rescue in custom_formatter'
	 4: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:241:in `require'
	 3: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rswag-specs-2.13.0/lib/rswag/specs/swagger_formatter.rb:5:in `<top (required)>'
	 2: from /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rswag-specs-2.13.0/lib/rswag/specs/swagger_formatter.rb:5:in `require'
	 1: from /Users/phil/src/bump/rails-hello-openapi/spec/swagger_helper.rb:3:in `<top (required)>'
/Users/phil/src/bump/rails-hello-openapi/spec/swagger_helper.rb:3:in `require': cannot load such file -- rails_helper (LoadError)
/Users/phil/.asdf/installs/ruby/2.7.0/bin/ruby -I/Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib:/Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-support-3.12.1/lib /Users/phil/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined failed
```

I have tried on Ruby 3.3 and then 2.7 wondering if it was related, but no difference.

## Steps to Test or Reproduce

  ```bash
  rails new rails-hello-world --api

  cd rails-hello-world
  ```

Add the rswag dependencies to the `Gemfile`.

  ```ruby
  # Gemfile
  gem 'rswag'
  ```

Install the new dependencies and run the rswag generator.

  ```bash
  bundle install

  bin/rails g rswag:install

  bin/rails g scaffold Widget name:string

  bin/rails db:migrate

  bin/rake rswag:specs:swaggerize
  ```

that should give you the above error.

## Expected behavior

Running `bin/rake rswag:specs:swaggerize` throws an error and according to the README it should generate OpenAPI, but no OpenAPI is generated.

## Dependency versions
The version of are you using for:
* Rswag: 2.13.0
* RSpec: 3.12.2
* Rails: 7.1.2
* Ruby: 2.7.0

**Comment by philsturgeon** [comment]
Just needed me to run `rails generate rspec:install`
