### ISSUE TITLE
Why does `rake rswag:specs:swaggerize` require a database connection?

### ISSUE THREAD

**Issue by zlesnr** [rswag/rswag#81]
I'm trying to generate the swagger documentation in a Dockerfile, but I don't have a database available at this step in the process and I'm seeing a database connection failure.  Is this avoidable?

**Comment by domaindrivendev** [comment]
can you provide a stack trace?

**Comment by zlesnr** [comment]
```
/Users/zlesnr/.rbenv/versions/2.3.1/bin/ruby -I/Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib:/Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
/Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `initialize': could not connect to server: Connection refused (PG::ConnectionBad)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `new'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:91:in `connection'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1042:in `needs_migration?'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:577:in `load_schema_if_pending!'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:592:in `block in maintain_test_schema!'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:823:in `suppress_messages'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:597:in `method_missing'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:592:in `maintain_test_schema!'
        from /Users/zlesnr/Code/myapp/spec/rails_helper.rb:28:in `<top (required)>'
        from /Users/zlesnr/Code/myapp/spec/swagger_helper.rb:1:in `require'
        from /Users/zlesnr/Code/myapp/spec/swagger_helper.rb:1:in `<top (required)>'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rswag-specs-1.4.0/lib/rswag/specs/swagger_formatter.rb:2:in `require'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rswag-specs-1.4.0/lib/rswag/specs/swagger_formatter.rb:2:in `<top (required)>'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/formatters.rb:222:in `require'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/formatters.rb:222:in `rescue in custom_formatter'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/formatters.rb:219:in `custom_formatter'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/formatters.rb:172:in `find_formatter'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/formatters.rb:141:in `add'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:828:in `add_formatter'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:117:in `block in load_formatters_into'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:117:in `each'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:117:in `load_formatters_into'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:23:in `configure'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:99:in `setup'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
Coverage report generated for RSpec to /Users/zlesnr/Code/myapp/coverage. 212 / 232 LOC (91.38%) covered.
/Users/zlesnr/.rbenv/versions/2.3.1/bin/ruby -I/Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib:/Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib /Users/zlesnr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined failed
```

**Comment by domaindrivendev** [comment]
There's nothing in rswag that requires a DB connection directly ... but it's an extension to rspec-rails "request/integration" specs and these run against a pretty much complete Rails stack, including a database connection.

Or another way of looking at it ... rswag is primarily a tool for "integration" testing that automatically generates Swagger.json as a byproduct. So there's kind of an assumption that you generate the Swagger in the same environment where you execute your integration tests.

Technically though, this isn't necessary as rswag doesn't need to execute the actual tests in order to generate the Swagger.json - the metadata data collected prior to invoking run_test! is sufficient. But, I haven't dug into what's required to make this possible. If you're interested in creating a PR, this would be a useful addition.

Regarding the Docker problem, I've encountered something similar before in a different context - I wanted to run `rake assets:precompile` as part of the Docker build process. But, in older versions of Rails a DB connection is required for this. I ended using a gem called nulldb get around this, informing the precompile command to use a nulldb adapter by environment variable. Given that rswag uses the rspec --dry-run flag during `swaggerize`, it won't actually run the tests and so the nulldb adapter would be sufficient.

This is what I did ...

```
# Dockerfile
RUN RAILS_ENV=acceptance RAILS_GROUPS=assets,nulldb_adapter DB_ADAPTER=nulldb bundle exec rake assets:precompile
```

You could potentially do something similar ...

```
# Dockerfile
RUN RAILS_ENV=test DB_ADAPTER=nulldb bundle exec rswag:specs:swaggerize
```

**Comment by zlesnr** [comment]
Adding the `DB_ADAPTER=nulldb` did not help in my case, testing locally just by stopping the database service and running the rake task.  The error looks identical, complaining about postgres port availability on localhost.

In the mean time, I've resorted to committing the swagger.json file to the repo, which requires a human to update it manually.  We also run the assets:precompile in the docker build process, so I'd thought something similar could be done for rswag and ran into the issue.

**Comment by domaindrivendev** [comment]
Is the Docker build part of your CI/CD pipeline? If so, I'm assuming it comes after a testing stage. Could you generate the Swagger files in this stage and then add it to during the Docker build along with the rest of the Rails code? Not sure if this is an option - just trying to think through the workflow.

It's also worth noting that it's ultimately something in rails_helper.rb (generated by rspec-rails) trying to access the DB. This file lives in your repo and so you have full control to add "test vs build" awareness where necessary. If you debug a little deeper you might be able to prevent a `require` somewhere based on an ENV variable that distinguishes between test/build environments

**Comment by domaindrivendev** [comment]
Long story short - no simple answer right now :)

**Comment by zlesnr** [comment]
Totally fair.  Generating the file during testing, then adding the file during the docker build could be an option.  Thanks for the information in any case.  Feel free to close the issue if there are no plans to address it.

**Comment by dev-zamir** [comment]
This worked for me 
`docker-compose run web rake rswag:specs:swaggerize`
where  `web` is a service defined in `docker-compose.yml` for rails server.

**Comment by lpwanw** [comment]
i got some trick
the `swagger_helper.rb` file required `rails_helper` and it run method `ActiveRecord::Migration.maintain_test_schema!` to check the db.
here my solution:
in `rails_helper.rb` add an ENV to skip checking db schema
`
ActiveRecord::Migration.maintain_test_schema! unless ENV.fetch("API_DOC_MODE", nil)
`
then add the ENV to rswag command
`rake rswag:specs:swaggerize API_DOC_MODE=true`

**Comment by oulhtak** [comment]
@lpwanw  answer is the right one
